name: Deploy para VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Configurar SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 31.97.23.50 > ~/.ssh/known_hosts

    - name: Rodar script de deploy na VPS
      run: |
        ssh -i ~/.ssh/id_ed25519 cidikley@31.97.23.50 "/var/www/techome.dev.br/deploy.sh"
